### ISSUE TITLE
Create Aggregation Statistics failed. (Aggregation Phase 3) EDIT: phase 4

### ISSUE THREAD

**Issue by michelescarlato** [ecrin-github/MDR_Aggregator#8]
Probably linked to 
https://github.com/ecrin-github/MDR_Aggregator/issues/6
and
https://github.com/ecrin-github/MDR_Aggregator/issues/7

```
31/08/2024 : 10:23 :   **** SETUP ****

31/08/2024 : 10:23 :   transfer data =  False
31/08/2024 : 10:23 :   create core =  False
31/08/2024 : 10:23 :   create json =  False
31/08/2024 : 10:23 :   do statistics =  True
31/08/2024 : 10:23 :   do iec =  False
31/08/2024 : 10:23 :   do indices =  False

31/08/2024 : 10:23 :   **** TABLE RECORD NUMBERS ****


31/08/2024 : 10:23 :   STATISTICS FOR CORE TABLES


31/08/2024 : 10:23 :   **** STUDY TABLES ****

31/08/2024 : 10:23 :   Studies: 901,484
31/08/2024 : 10:23 :   Study Identifiers: 1,765,548
31/08/2024 : 10:23 :   Study Titles: 1,810,973
31/08/2024 : 10:23 :   Study Topics: 1,386,891
31/08/2024 : 10:23 :   Study Features: 3,054,420
31/08/2024 : 10:23 :   Study Conditions: 24,286,189
31/08/2024 : 10:23 :   Study ICD Records: 782,606
31/08/2024 : 10:23 :   Study People: 1,095,687
31/08/2024 : 10:23 :   Study Organisations: 1,531,312
31/08/2024 : 10:23 :   Study Relationships: 15,964
31/08/2024 : 10:23 :   Study Countries: 1,173,791
31/08/2024 : 10:23 :   Study Locations: 3,152,378

31/08/2024 : 10:23 :   **** OBJECT TABLES ****

31/08/2024 : 10:23 :   Data Objects: 1,437,840
31/08/2024 : 10:23 :   Object Instances: 1,568,210
31/08/2024 : 10:23 :   Object titles: 345,012
31/08/2024 : 10:23 :   Object Datasets: 2,116
31/08/2024 : 10:23 :   Object Dates: 4,382,487
31/08/2024 : 10:23 :   Object Relationships: 0
31/08/2024 : 10:23 :   Object Rights: 0
31/08/2024 : 10:23 :   Object People: 2,622,121
31/08/2024 : 10:23 :   Object Organisations: 17,504
31/08/2024 : 10:23 :   Object Topics: 3,367,877
31/08/2024 : 10:23 :   Object Descriptions: 270,459
31/08/2024 : 10:23 :   Object Identifiers: 695,467

31/08/2024 : 10:23 :   **** STUDY-OBJECT LINKAGE ****

31/08/2024 : 10:23 :   Study-Object Links: 1,568,796


31/08/2024 : 10:23 :   **** OBJECT TYPE NUMBERS ****

31/08/2024 : 10:23 :   	13	Trial registry entry: 960,257
31/08/2024 : 10:23 :   	12	Journal article - unspecified: 270,616
31/08/2024 : 10:23 :   	28	Trial registry results summary: 95,373
31/08/2024 : 10:23 :   	79	Results or CSR summary: 26,710
31/08/2024 : 10:23 :   	11	Study protocol: 18,514
31/08/2024 : 10:23 :   	74	Protocol SAP: 18,499
31/08/2024 : 10:23 :   	22	Statistical analysis plan: 14,177
31/08/2024 : 10:23 :   	18	Informed consent forms: 9,897
31/08/2024 : 10:23 :   	38	Study overview: 4,202
31/08/2024 : 10:23 :   	134	Website: 3,820
31/08/2024 : 10:23 :   	19	Patient information sheets: 3,487
31/08/2024 : 10:23 :   	26	Clinical study report: 2,491
31/08/2024 : 10:23 :   	80	Individual participant data: 1,997
31/08/2024 : 10:23 :   	202	Journal article - results: 1,745
31/08/2024 : 10:23 :   	31	Data dictionary: 1,602
31/08/2024 : 10:23 :   	76	Protocol SAP ICF: 1,103
31/08/2024 : 10:23 :   	30	Annotated data collection forms: 918
31/08/2024 : 10:23 :   	88	Summary of results for public: 534
31/08/2024 : 10:23 :   	201	Journal article - protocol: 365
31/08/2024 : 10:23 :   	301	Sample Description: 284
31/08/2024 : 10:23 :   	75	Protocol ICF: 279
31/08/2024 : 10:23 :   	210	Preprint article: 231
31/08/2024 : 10:23 :   	42	Redacted protocol: 159
31/08/2024 : 10:23 :   	204	Journal article - review: 156
31/08/2024 : 10:23 :   	37	Other text based object: 116
31/08/2024 : 10:23 :   	203	Journal article - interim results: 90
31/08/2024 : 10:23 :   	0	Not yet known: 73
31/08/2024 : 10:23 :   	69	Aggregated result dataset: 52
31/08/2024 : 10:23 :   	43	Redacted SAP: 45
31/08/2024 : 10:23 :   	27	Redacted clinical study report: 30
31/08/2024 : 10:23 :   	XX	Total of smaller categories (n<30): 18

31/08/2024 : 10:23 :   SOURCE DATABASE DATA
31/08/2024 : 10:23 :   The first of these two numbers is the number of records in the data base (AD) table.
                       The second is the number of records transferred to the core MDR data from each source.
                       They are often less than the total number of records in the DB because of study duplication.
                       For some DBs, e.g. Biolincc, EUCTR, which have many multiple registrations, this effect is marked.
                       Conversely, for ClinicalTrials.gov, where all adata is used, the numbers are equal
31/08/2024 : 10:23 :   ClinicalTrials.gov

31/08/2024 : 10:23 :   Studies: 			506,420			506,420
31/08/2024 : 10:24 :   Study Identifiers: 	1,156,483		1,156,483
31/08/2024 : 10:24 :   Study Titles: 		1,037,984		1,037,984
31/08/2024 : 10:24 :   Study People: 		581,202			581,202
31/08/2024 : 10:24 :   Study Organisations: 805,521			805,521
31/08/2024 : 10:24 :   Study Topics: 		1,314,607		1,314,607

31/08/2024 : 10:25 :   **** UNHANDLED EXCEPTION ****


+++++++++++++++++++++++++++++++++++++++
31/08/2024 : 10:25 :   ***ERROR*** MDR_Aggregator application aborted

Exception while reading from stream
InnerException Message:
Timeout during reading attempt

   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|222_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar()
   at Dapper.SqlMapper.ExecuteScalarImpl[T](IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 2877
   at Dapper.SqlMapper.ExecuteScalar[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 493
   at MDR_Aggregator.MonDataLayer.GetRecNum(String table_name, String source_conn_string) in C:\Users\ecrinadmin\RiderProjects\MDR_Aggregator\LoggingHelpers\MonitorDataLayer.cs:line 133
   at MDR_Aggregator.StatisticsBuilder.WriteOutSourceDataTableSummaries() in C:\Users\ecrinadmin\RiderProjects\MDR_Aggregator\AggDBBuilders\StatisticsBuilder.cs:line 206
   at MDR_Aggregator.Aggregator.AggregateData(Options opts) in C:\Users\ecrinadmin\RiderProjects\MDR_Aggregator\TopLevelClasses\Aggregator.cs:line 266
   at Program.<Main>$(String[] args) in C:\Users\ecrinadmin\RiderProjects\MDR_Aggregator\TopLevelClasses\Program.cs:line 62
+++++++++++++++++++++++++++++++++++++++


31/08/2024 : 10:25 :   **** CLOSING LOG ****
```

**Comment by michelescarlato** [comment]
My bad, this is phase 4.
I should still run Create Core MDR DB before this phase.

**Comment by michelescarlato** [comment]
[AG -S 2024-08-31 184155.log](https://github.com/user-attachments/files/16825465/AG.-S.2024-08-31.184155.log)

Still the same error is there, despite completing (with the known errors mentioned in issue #7 ) phase 3.

I am adding a timeout to the `GetRecNum` function.
```c#
public int GetRecNum(string table_name, string source_conn_string)
    {
        string sql_string = "SELECT count(*) from ad." + table_name;
        using var conn = new NpgsqlConnection(source_conn_string);
        var rec_num = conn.ExecuteScalar<int?>(sql_string, commandTimeout: 240);
        return rec_num ?? 0;
    }
```

**Comment by michelescarlato** [comment]
The timeout seems to have fixed the current error.
![image](https://github.com/user-attachments/assets/3ef42656-79a4-41ef-9578-a414e2dff84f)

[AG -S 2024-08-31 185657.log](https://github.com/user-attachments/files/16825468/AG.-S.2024-08-31.185657.log)


Running phase 5: Create Index.

**Comment by michelescarlato** [comment]
The build with the timeout is in `net8.0/` directory.

The day 8th September failed again for with the same error.
I restarted changing the path of the executable into:

`C:\Users\ecrinadmin\source\repos\MDR_Aggregator\bin\Debug\net8.0\MDR_Aggregator.exe`
![image](https://github.com/user-attachments/assets/63783964-2b50-4eb0-a831-4407dbe0db5a)

And it runs properly.
I attach both logs.

**Comment by michelescarlato** [comment]
[AG -S 2024-09-08 160000.log](https://github.com/user-attachments/files/16925946/AG.-S.2024-09-08.160000.log)
[AG -S 2024-09-09 073624.log](https://github.com/user-attachments/files/16925947/AG.-S.2024-09-09.073624.log)

Re-running indexing now (linked to issue #10)
